Tasks/Models/BaseModel.cs
namespace Tasks.Models
{
    public class BaseModel
    {
        public int Id { get; set; }
    }
}

Tasks/Models/FilterVM.cs
namespace Tasks.Models
{
    public class FilterVM
    {
        public string Search { get; set; }
        public int StateOrder { get; set; }
        public string StateName { get; set; }
    }
}

Tasks/Models/TaskList.cs
using System.Collections.Generic;

namespace Tasks.Models
{
    public class TaskList
    {
        public List<TaskModel> Items { get; set; }
        public List<TaskModel> ExpiredTaskItems { get; set; }
        public Dictionary<int, string> States { get; set; }
        public FilterVM Filter { get; set; }
    }
}

Tasks/Models/TaskModel.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace Tasks.Models
{
    public class TaskModel : BaseModel
    {
        public string Title { get; set; }
        public string Describe { get; set; }
        public int StateId { get; set; }
        [BindProperty]
        public DateTime StartDate { get; set; }
    }
}

Tasks/ViewModels/DisplaySection.cs
using System.Collections.Generic;
using Tasks.Models;

namespace Tasks.ViewModels
{
    public class DisplaySection
    {  
        public List<TaskModel> Items { get; set; }
        public Dictionary<int, string> States { get; set; }
        public string StyleValue { get; set; }
    }
}

Tasks/Components/YearViewComponent.cs
using System;

namespace Tasks.Components
{
    public class YearViewComponent
    {
        public string Invoke() {
            return DateTime.Now.Year.ToString(); ;
        }
    }
}

Tasks/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Tasks.Models.Auth;

namespace Tasks.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Login() {
            return View();
        }

        public IActionResult Register(User user)
        {
            if (ModelState.IsValid)
                return Content($"{user.Name} - {user.Email}");
            else
                return View(user);
        }
    }
}

Tasks/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;

namespace Tasks.Controllers
{
    //public class CalendarController : Controller
    //{
    //    public IActionResult GetCalendar() {
    //        return View();
    //    }
    //}
}

Tasks/Controllers/HistotyController.cs
using Microsoft.AspNetCore.Mvc;

namespace Tasks.Controllers
{
    public class HistotyController : Controller
    {
        public IActionResult GetHistory()
        {
            return View();
        }
    }
}

Tasks/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Tasks.Services;
using Tasks.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Tasks.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITasksServices _tasksService;
        private readonly Dictionary<int, string> _states;

        public HomeController(ITasksServices tasksService)
        {
            _tasksService = tasksService;
            _states = new Dictionary<int, string>() {
                    { 0, "All" },
                    { 1, "To do" },
                    { 2, "In Progress" },
                    { 3, "Done" },
                    { 4, "Expired task"}
                };
        }

        public IActionResult Index(FilterVM filter)
        {
            ICollection<TaskModel> taskItems = _tasksService.GetTasks(filter);

            var response = new TaskList()
            {
                Filter = filter,
                States = _states,
                Items = taskItems.Where(t => t.StartDate == DateTime.Now.Date).OrderBy(t => t.StateId).ToList(),
                ExpiredTaskItems = taskItems.Where(t => t.StartDate < DateTime.Now.Date && t.StateId != 3).ToList()
            };

            ViewBag.Search = filter.Search;
            ViewBag.IsAuth = false;
            //filter.StateName = _states[filter.StateOrder];
            
            return View(taskItems);
        }

        [HttpGet]
        public IActionResult Get(int id)
        {
            TaskModel task = _tasksService.Get(id);
            if (task == null)
            {
                return BadRequest();
            }

            return View(task);
        }

        [HttpPost]
        public IActionResult Create(TaskModel task)
        {
            if (task == null)
            {
                return BadRequest();
            }

            if (!string.IsNullOrEmpty(task.Title) || !string.IsNullOrEmpty(task.Describe))
            {
                _tasksService.Add(task);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Update(TaskModel task)
        {
            if (task == null)
            {
                return BadRequest();
            }

            if (!_tasksService.Update(task))
            {
                return BadRequest();
            }

            return RedirectToAction("Index");
        }

        public IActionResult UpdateState(int id, int stateId)
        {
            if (!_tasksService.UpdateState(id, stateId))
            {
                return BadRequest();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (!_tasksService.Delete(id))
            {
                return BadRequest();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Calendar()
        {
            return View();
        }

        public IActionResult History()
        {
            return View();
        }
    }
}

Tasks/Views/Home/History.cshtml
@{
    ViewData["Title"] = "History";
    ViewData["HistoryActive"] = "active";
}

<div class="col-sm-3">
    History
</div>
  

Tasks/Views/Home/Index.cshtml
@model TaskList;
@using Tasks.HtmlHelper

@{
    ViewData["Title"] = "Index";
    ViewData["IndexActive"] = "active";
}

<div>
    <h3>For @DateTime.Now.ToString("MMMM dd", new System.Globalization.CultureInfo("en-US"))</h3>
    <div class="dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
            @Model.Filter.StateName
        </button>
        <ul class="dropdown-menu">
            @foreach (var state in Model.States)
            {
                <li>
                    <a asp-action="Index" asp-route-stateOrder="@state.Key" class="dropdown-item @(Model.Filter.StateOrder == state.Key ? "active" : "")">@state.Value</a>
                </li>
            }
        </ul>
    </div>
</div>
<div class="page-content page-container">
    <div class="row d-flex mt-2 justify-content-center">
        <div class="row col-sm-8 w-100 m-0">
            @if (Model.ExpiredTaskItems.Any())
            {
                @Html.StateName("Expired task")
                await Html.RenderPartialAsync("PartialView/_DisplaySection", new DisplaySection { Items = Model.ExpiredTaskItems, States = Model.States, StyleValue = "border-danger" });
            }

            @for (int i = 1; i <= 3; i++)
            {
                if (Model.Items.Any(t => t.StateId == i))
                {
                    @Html.StateName(Model.States[i]);
                    await Html.RenderPartialAsync("PartialView/_DisplaySection", new DisplaySection { Items = Model.Items.Where(t => t.StateId == i).ToList(), States = Model.States });
                }
                else
                {
                    @if (Model.Filter.StateOrder == i || Model.Filter.StateOrder == 0)
                    {
                        @Html.StateName(Model.States[i]);
                        <p>Empty</p>
                    }
                }
            }
        </div>
    </div>
</div>

Tasks/Views/Home/PartialView/_AddTaskMW.cshtml
<div class="modal" id="ModalTask">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form id="form" asp-antiforgery="true" asp-controller="Home" asp-action="Create" method="post">
                <div class="modal-header">
                    <select name="stateId" class="form-select w-25">
                        <option value="1">To do</option>
                        <option value="2">In Progress</option>
                        <option value="3">Done</option>
                    </select>
                    <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="form-floating mb-3">
                        <input name="Title" type="text" class="form-control" id="floatingInput" placeholder="Enter title">
                        <label for="floatingInput">Enter title</label>
                    </div>
                    <div class="form-floating">
                        <textarea name="Describe" class="form-control" placeholder="Describe your task" id="floatingTextarea2" style="height: 100px"></textarea>
                        <label for="floatingTextarea2">Describe your task</label>
                    </div>
                    <div class="form-floating">
                        <input name="StartDate" id="floatingDate" type="date" class="form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" id="add" value="Add" class="btn btn-outline-success" data-bs-dismiss="modal">
                </div>
            </form>
        </div>
    </div>
</div>

Tasks/Views/Home/PartialView/_DisplaySection.cshtml
@model DisplaySection

@foreach (var task in Model.Items)
{
    <div class="col-sm-3 pt-1">
        <div class="card @(Model.StyleValue ?? "")">
            <div class="dropdown p-1">
                <a class="btn btn-outline-light border" style="color: black; padding: 0px 8px 0px 8px;" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                    @Model.States[task.StateId]
                </a>
                <ul class="dropdown-menu">
                    @foreach (var state in Model.States.Skip(1))
                    {
                        <li><a asp-action="UpdateState" asp-route-id="@task.Id" asp-route-stateId="@state.Key" class="dropdown-item">@state.Value</a></li>
                    }
                </ul>
            </div>
            <div class="btn-group w-50 position-absolute top-0 end-0" role="group" aria-label="Basic mixed styles example">
                <a asp-controller="Home" asp-action="Delete" asp-route-id="@task.Id" class="btn btn-outline-light">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" color="#ff000078" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                    </svg>
                </a>
                <a onclick="editMW(@task.Id, '@task.Title', '@task.Describe', '@task.StartDate.ToString("yyyy-MM-dd")')" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#ModalTask">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" color="#000000a6" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                    </svg>
                </a>
            </div>
            <div class="card-body cut-text" data-date="date-">
                <h5 class="card-title mTitlet-3">@task.Title</h5>
                <p class="card-text">@task.Describe</p>
            </div>
        </div>
    </div>
}

Tasks/Views/Home/_AddTaskMW.cshtml
<div class="modal" id="ModalTask">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form id="form" asp-antiforgery="true"  asp-controller="Home" asp-action="Create" method="post">
                <div class="modal-header">
                    <h5 class="card-title">New task</h5>
                    <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="form-floating mb-3">
                        <input name="Title" type="text" class="form-control" id="floatingInput" placeholder="Enter title">
                        <label for="floatingInput">Enter title</label>
                    </div>
                    <div class="form-floating">
                        <textarea name="Describe" class="form-control" placeholder="Describe your task" id="floatingTextarea2" style="height: 100px"></textarea>
                        <label for="floatingTextarea2">Describe your task</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-success" data-bs-dismiss="modal">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

Tasks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <asp:ContentPlaceHolder ID="Stylesheets" runat="server">
        <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="~/css/style.css">
    </asp:ContentPlaceHolder>

    @*datepicker*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <header class="mb-3 border-bottom">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-between">
                <a href="/" class="mb-2 mb-lg-0">
                    <img class="bi me-2" width="63" height="64" src="~/img/tasks.png" />
                </a>
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <input type="search" name="Search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search" value="@ViewBag.Search">
                </form>

                @if (ViewBag.IsAuth)
                {
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Sign out</a></li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="text-end">
                        <a asp-controller="Auth" asp-action="Login" class="btn btn-outline-secondary me-2">Login</a>
                        <a class="btn btn-warning">Sign-up</a>
                    </div>
                }
            </div>
        </div>
    </header>
    <div class="container pt-md-1 pb-md-4">
        <div class="row">
            <div class="col-3">
                <ul class="nav flex-column nav-pills nav-tabs">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link link-secondary @ViewData["IndexActive"]">Tasks</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Calendar" class="nav-link link-secondary @(@ViewData["CalendarActive"])">Calendar</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="History" class="nav-link link-secondary @(@ViewData["HistoryActive"])">History</a>
                    </li>
                </ul>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="button" class="btn btn-outline-primary mt-3" onclick="clearMW()" data-bs-toggle="modal" data-bs-target="#ModalTask">
                        New task
                    </button>
                </div>
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </div>
    @*<footer class="text-white fixed-bottom m-0">
            <div class="container bg-dark d-flex justify-content-around pt-3">
                <p>© @await Component.InvokeAsync("Year") Company, Tasks. All rights reserved.</p>
                <ul class="list-unstyled d-flex">
                    <li class="ms-3"><a class="link-dark" href="#"><img class="bi" width="24" height="24" src="~/img/twitter.png"></a></li>
                    <li class="ms-3"><a class="link-dark" href="#"><img class="bi" width="24" height="24" src="~/img/instagram.png"></a></li>
                    <li class="ms-3"><a class="link-dark" href="#"><img class="bi" width="24" height="24" src="~/img/facebook.png"></a></li>
                </ul>
            </div>
        </footer>*@

    @{await Html.RenderPartialAsync("PartialView/_AddTaskMW");}

    <script type="text/javascript">
        function clearMW() {
            document.getElementById("floatingInput").value = "";
            document.getElementById("floatingTextarea2").value = "";
            document.getElementById("add").value = "Add";
            document.getElementById("floatingDate").value = '@DateTime.Now.ToString("yyyy-MM-dd")';
        }
        function editMW(id, title, describe, date) {
            var formModal = document.getElementById("form");
            formModal.setAttribute("action", "Home/Update/" + id);

            document.getElementById("add").value = "Save"
            document.getElementById("floatingInput").value = title;
            document.getElementById("floatingTextarea2").value = describe;
            document.getElementById("floatingDate").value = date;
        }
    </script>
</body>
</html>